<div id="load" class="load"></div>

<div id="perfil" class="container" hidden>
    <div class="row">
        <div class="profile-info col-md-3">
            <div class="photo">
                <span><img src="../../img/user-natanfoleto.jfif"/></span>
            </div>

            <div class="usuario-logado">
                <h4 id="name-photo"></h4>
                <p id="email-photo"></p>
            </div>

            <div class="logout mt-4">
                <button id="btnLogout" class="btn btn-perfil col-md-12">
                    Logout
                </button>
            </div>

            <div class="star">
                <i class="fas fa-star"></i>
                <p class="btn btn-success">FREE</p>
            </div>
            
        </div>

        <div class="profile-form col-md-9">
            <div class="user-details">
                <div class="info">
                    <div class="info-title">
                        <h4>Perfil</h4>
                        <hr/>
                    </div>
                    
                    <div class="info-body row">
                        <div class="info-right col-md-6">
                            <h5>Nome</h5>
                            <p id="name-perfil"></p>

                            <h5>Data de Nascimento</h5>
                            <p id="data-perfil"></p>

                            <h5>CPF</h5>
                            <p id="cpf-perfil"></p>

                            <h5>Celular</h5>
                            <p id="phone-perfil"></p>

                            <h5>E-mail</h5>
                            <p id="email-perfil"></p>

                            <h5>Status do Usuário</h5>
                            <p id="status-perfil"></p>
                        </div>

                        <div class="info-left col-md-6">
                            <h5>Grupo de Usuário</h5>
                            <p id="grupo-perfil"></p>

                            <h5>Data de Cadastro</h5>
                            <p id="dataAdd-perfil"></p>

                            <h5>Ultima Alteração</h5>
                            <p id="dataEdt-perfil"></p>

                            <button class="btn btn-perfil"> Alterar Senha</button>
                        </div>
                    </div>
                    <hr/>
                    <div class="info-footer">
                        <button class="btn btn-perfil col-md-12"> Registros de Atividades</button>
                        <p>Alterações no seu perfil, podem ser feitas na aba {Cadastros>Usuários}.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer"> </div>
                            
</div>

<script src="../../js/Controller/CPerfil.js"> </script>
          