<div class="container">

    <div class="row">
        <div class="profile-info col-md-4">
            <div class="photo mt-2">

            </div>
    
        </div>

        <div class="profile-form col-md-8">
            <div class="usuario-logado">
                <h4>Nome</h4>
                <h6>Natan de Souza Foleto</h6>
            </div>  
        </div>
    </div>

    <div class="footer"> </div>
                            
</div>

<script src="../../js/Controller/CPerfil.js"> </script>
          