<div class="container">

    <div class="row">
        <div class="profile-info col-md-3">
            <div class="photo">
                <span><img src="../../img/user-natanfoleto.jfif"/></span>
            </div>

            <div class="usuario-logado">
                <h4>Natan Foleto</h4>
                <p>natanfoleto2015@hotmail.com</p>
            </div>

            <div class="logout mt-4">
                <button class="btn btn-perfil col-md-12">
                    Logout
                </button>
            </div>

            <div class="star">
                <i class="fas fa-star"></i>
                <p class="btn btn-success">FREE</p>
            </div>
            
        </div>

        <div class="profile-form col-md-9">
            <div class="user-details">
                <div class="info">
                    <div class="info-title">
                        <h4>Perfil</h4>
                        <hr/>
                    </div>
                    
                    <div class="info-body row">
                        <div class="info-right col-md-6">
                            <h5>Nome</h5>
                            <p>Natan de Souza Foleto</p>

                            <h5>Data de Nascimento</h5>
                            <p>10/07/1999</p>

                            <h5>CPF</h5>
                            <p>48092926816</p>

                            <h5>Celular</h5>
                            <p>(17) 992424418</p>

                            <h5>E-mail</h5>
                            <p>natanfoleto2015@hotmail.com</p>

                            <h5>Status do Usuário</h5>
                            <p>Ativo no Sistema</p>
                        </div>
                        <div class="info-left col-md-6">
                            <h5>Grupo de Usuário</h5>
                            <p>Desenvolvedor</p>

                            <h5>Data de Cadastro</h5>
                            <p>1999-01-01 às 10:30:00</p>

                            <h5>Ultima Alteração</h5>
                            <p>1999-01-01 às 10:30:00</p>

                            <button class="btn btn-perfil"> Alterar Senha</button>
                        </div>
                    </div>
                    <hr/>
                    <div class="info-footer">
                        <button class="btn btn-perfil col-md-12"> Registros de Atividades</button>
                        <p>Alterações no seu perfil, podem ser feitas na aba {Cadastros>Usuários}.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer"> </div>
                            
</div>

<script src="../../js/Controller/CPerfil.js"> </script>
          