<html>
	<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title> iCloth </title>
        
        <!-- Fontes Personalizadas -->
        <link href="VHomeSite.css" rel="stylesheet">

        <!-- Bootstrap CSS -->
        <link href="../src/Views/css/lib/bootstrap.min.css" rel="stylesheet">

        <!-- Animate CSS -->
        <link href="../src/Views/css/lib/animate.min.css" rel="stylesheet">

        <!-- Font Awesome JS-->
        <script src="../src/Views/js/lib/fontawesome.min.js"></script>

        <!-- Jquery -->
        <script src="../src/Views/js/lib/jquery.min.js"></script>

        <!-- Bootstrap JS -->
        <script src="../src/Views/js/lib/bootstrap.min.js"></script>

    </head>

    <body>
        <div class="header">
            <div class="container">
                <div class="row mt-4 mb-4">
                    <div class="col-md-4 logo">
                        <div class="title">
                            <h1> ROOTS </h1>
                        </div>
                    </div>

                    <div class="col-md-5 search" id="container"> 
                        <form class="form-inline form">
                            <div class="input-group">
                                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-success" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="col-md-3 menu">
                        <div class="link">
                            <a href="#"> Register </a> /
                            <a href="../src/Views/html/Login/VLogin.phtml"> Sing in </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-right">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
                    <i class="fas fa-bars"></i>
                </button>

                <div class="nav collapse navbar-collapse" id="navbarNav">
                    <ul class="ul-nav navbar-nav">
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">HOME <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">SHOP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">SOBRE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">CONTATO</a>
                        </li>
                    </ul>
                </div>
            </div>        
        </nav>    

        <div id="carousel-main" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-main" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-main" data-slide-to="1"></li>
                <li data-target="#carousel-main" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="../src/Views/img/carousel-1.jpg">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Aproveite todas as promoções</h3>
                        <h5>Em até 12x sem juros!</h5>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="../src/Views/img/carousel-2.png">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Aproveite todas as promoções</h3>
                        <h5>Em até 12x sem juros!</h5>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="../src/Views/img/carousel-3.jpg">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Aproveite todas as promoções</h3>
                        <h5>Em até 12x sem juros!</h5>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carousel-main" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-main" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="footer mt-5">
            <div class="row social-links">
                <div class="container d-none d-lg-block">
                    <a href="https://goo.gl/maps/yRYzMLJRAqiiYU749" 
                    target="_blank" class="maps">
                        <i class="fas fa-map-marked-alt"></i><span>localização</span>
                    </a>

                    <a href="https://www.facebook.com/profile.php?id=100017458895663" 
                    target="_blank" class="facebook">
                        <i class="fab fa-facebook-f"></i><span>facebook</span>
                    </a>

                    <a href="https://api.whatsapp.com/send?phone=5516991011372" 
                    target="_blank" class="whatsapp">
                        <i class="fab fa-whatsapp"></i><span>whatsapp</span>
                    </a>

                    <a href="https://www.instagram.com/lojaroots1/" 
                    target="_blank" class="instagram">
                        <i class="fab fa-instagram"></i><span>instagram</span>
                    </a>
        
                    <!-- <a href="" target="_blank" class="youtube">
                        <i class="fab fa-youtube"></i><span>youtube</span>
                    </a> -->
                </div>  
            </div>			

            <div class="footer-p container text-center pt-5">
                <div class="container">
                    <p> 
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        | Todos os direitos reservados.
                    </p>
                </div>
            </div>


		</div>
        
    </body>
        
    <script src="../../js/Mochila/Util.js"></script>
    <script src="../../js/Mochila/xhttp.js"></script>
    <script src="../../js/Controller/CHome.js"></script>
    
</html>
        
<script src="../../js/Controller/CHomeSite.js"> </script>

