<html>
	<head>
		<title> Roots </title>

		<!-- Fontes Personalizadas -->
		<link href="VMenu.css" rel="stylesheet">

		<!-- Font Awesome -->
		<script src="../src/Views/js/lib/fontawesome.min.js"></script>
	</head>

	<body>

		<div class="box">
			<a href="../src/Views/html/Login/VLogin.phtml" class="btn" title="Entrar no iCloth" target="_blank">
				<i class="fas fa-sign-in-alt"></i>
			</a>
		</div>

	</body>
</html>
