<html>
	<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title> iCloth </title>
        
        <!-- Fontes Personalizadas -->
        <link href="VHomeSite.css" rel="stylesheet">

        <!-- Bootstrap CSS -->
        <link href="../../css/lib/bootstrap.min.css" rel="stylesheet">

        <!-- Animate CSS -->
        <link href="../../css/lib/animate.min.css" rel="stylesheet">

        <!-- Font Awesome -->
        <script src="../../js/lib/fontawesome.min.js"></script>

        <!-- Jquery -->
        <script src="../../js/lib/jquery.min.js"></script>

        <!-- Bootstrap JS -->
        <script src="../../js/lib/bootstrap.min.js"></script>

    </head>

    <body>
        <div class="header">
            <div class="container">
                <div class="row mt-4 mb-4">
                    <div class="col-md-4 logo">
                        <div class="title">
                            <h1> ROOTS </h1>
                        </div>
                    </div>

                    <div class="col-md-5 search" id="container"> 
                        <form class="form-inline form">
                            <div class="input-group">
                                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-success" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="col-md-3 menu">
                        <div class="link">
                            <a href="#"> Register </a> /
                            <a href="#"> Sing in </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">Contato</a>
                        </li>
                    </ul>
                </div>
            </div>        
        </nav>    

        <div id="carousel-main" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-main" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-main" data-slide-to="1"></li>
                <li data-target="#carousel-main" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="../../img/carousel-1.jpg" alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Aproveite todas as promoções</h3>
                        <h5>Em até 12x sem juros!</h5>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="../../img/carousel-2.png" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Aproveite todas as promoções</h3>
                        <h5>Em até 12x sem juros!</h5>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="../../img/carousel-3.jpg" alt="Third slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Aproveite todas as promoções</h3>
                        <h5>Em até 12x sem juros!</h5>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carousel-main" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-main" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div> 
        
    </body>
        
    <script src="../../js/Mochila/Util.js"></script>
    <script src="../../js/Mochila/xhttp.js"></script>
    <script src="../../js/Controller/CHome.js"></script>
    
</html>
        


