<html>
	<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title> iCloth </title>
        
        <!-- Fontes Personalizadas -->
        <link href="VHome.css" rel="stylesheet">
        <link href="../../css/Mochila/Comun.css" rel="stylesheet">
        <link href="../Usuarios/VUsuarios.css" rel="stylesheet">
        <link href="../Perfil/VPerfil.css" rel="stylesheet">

        <!-- Bootstrap CSS -->
        <link href="../../css/lib/bootstrap.min.css" rel="stylesheet">

        <!-- Animate CSS -->
        <link href="../../css/lib/animate.min.css" rel="stylesheet">

        <!-- DataTable CSS -->
        <link href="../../css/lib/datatables.css" rel="stylesheet">

        <!-- Noty CSS -->
        <link href="../../css/lib/noty.css" rel="stylesheet">

        <!-- Font Awesome -->
        <script src="../../js/lib/fontawesome.min.js"></script>

        <!-- Jquery -->
        <script src="../../js/lib/jquery.min.js"></script>

        <!-- DataTable JS -->
        <script src="../../js/lib/datatables.min.js"></script>

        <!-- Noty JS -->
        <script src="../../js/lib/noty.min.js"></script>

        <!-- Bootstrap JS -->
        <script src="../../js/lib/bootstrap.min.js"></script>

    </head>

    

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fadeInLeft animated">
            <div class="container">

                <a class="navbar-brand d-none d-md-block" href="#">
                    <img src="../../img/logo.png">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Inicio <span class="sr-only">(Página atual)</span></a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown">
                                Produtos
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Lista de Produto</a>
                                <a class="dropdown-item" href="#">Grupo de Produtos</a>
                            </div>
                        </li>
                    
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown">
                                Equipe
                            </a>

                            <div class="dropdown-menu">
                                <a id="l_usuarios" class="dropdown-item" href="#">Lista de Usuários</a>
                                <a class="dropdown-item" href="#">Grupo de Usuários</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown">
                                Clientes
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Lista de Clientes</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown">
                                Fornecedores
                            </a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown">
                                Relatórios
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Produtos</a>
                                <a class="dropdown-item" href="#">Equipe</a>
                                <a class="dropdown-item" href="#">Clientes</a>
                                <a class="dropdown-item" href="#">Fornecedores</a>
                                <a class="dropdown-item" href="#">Registro de Atividades</a>
                            </div>
                        </li>
                    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="navDrop">
                                <i class="fas fa-user-circle"></i>
                            </a>
                            <div class="dropdown-menu">
                                <a id="l_perfil" class="dropdown-item" href="">
                                    <strong> Conectado </strong> como <br> <strong> Natan Foleto </strong>
                                </a>      
                                <hr>      
                                <a class="dropdown-item" href="">
                                    <i class="fas fa-cog"></i> Configurações
                                </a>
                                <a id="l_logout" class="dropdown-item" href="">
                                    <i class="fas fa-sign-out-alt"></i> Sair 
                                </a>                                
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <div class="container" id="container">
            
        </div>
        
    </body>
        
    <script src="../../js/Mochila/Util.js"></script>
    <script src="../../js/Mochila/xhttp.js"></script>
    <script src="../../js/Controller/CHome.js"></script>
    
</html>
        


