<html>
	<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title> iCloth </title>
        
        <!-- Fontes Personalizadas -->
        <link href="VHome.css" rel="stylesheet">

        <!-- Bootstrap CSS -->
        <link href="../../css/lib/bootstrap.min.css" rel="stylesheet">

        <!-- Animate CSS -->
        <link href="../../css/lib/animate.min.css" rel="stylesheet">

        <!-- Font Awesome -->
        <script src="../../js/lib/fontawesome.min.js"></script>

        <!-- Jquery -->
        <script src="../../js/lib/jquery.min.js"></script>

        <!-- Bootstrap JS -->
        <script src="../../js/lib/bootstrap.min.js"></script>

    </head>

    <body>
        <nav class="navbar navbar-expand-sm navbar-light bg-light fadeInLeft animated">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <span><img src="../../img/brand-roots.png"></span>
                </a>
                
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                    </li>

                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link"> <!--data-toggle="dropdown" -->
                                Cadastros
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Grupo de Produtos</a>
                                <a class="dropdown-item" href="#">Produtos</a>
                                <a class="dropdown-item" href="#">Estoque</a>
                                <a class="dropdown-item" href="#">Fornecedores</a>
                            </div>
                        </div>
                    </li> 

                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link">
                                Encomendas
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Vizulizar Encomendas</a>
                                <a class="dropdown-item" href="#">Encomendas Aprovadas</a>
                                <a class="dropdown-item" href="#">Encomendas Reprovadas</a>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link">
                                Estoque
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Vizualizar Estoque</a>
                                <a class="dropdown-item" href="#">Baixa</a>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link">
                                Relatórios
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Produtos</a>
                                <a class="dropdown-item" href="#">Clientes</a>
                                <a class="dropdown-item" href="#">Baixas</a>
                                <a class="dropdown-item" href="#">Encomendas</a>
                                <a class="dropdown-item" href="#">Registro de Atividades</a>
                            </div>
                        </div>
                    </li> 

                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link">
                                Configurações
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Perfil</a>
                                <a class="dropdown-item" href="#">Permissões</a>
                                <a class="dropdown-item" href="#">Sair</a>
                            </div>
                        </div>
                    </li> 

                </ul>
            </div>
        </nav>

        <div class="container">
            
        </div>
        
    </body>
        
    <script src="../../js/Mochila/Util.js"></script>
    <script src="../../js/Mochila/xhttp.js"></script>
    <script src="../../js/Controller/CHome.js"></script>

</html>
        


