<html>
	<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title> iCloth </title>
        
        <!-- Fontes Personalizadas -->
        <link href="VHomeSite.css" rel="stylesheet">

        <!-- Bootstrap CSS -->
        <link href="../../css/lib/bootstrap.min.css" rel="stylesheet">

        <!-- Animate CSS -->
        <link href="../../css/lib/animate.min.css" rel="stylesheet">

        <!-- Font Awesome -->
        <script src="../../js/lib/fontawesome.min.js"></script>

        <!-- Jquery -->
        <script src="../../js/lib/jquery.min.js"></script>

        <!-- Bootstrap JS -->
        <script src="../../js/lib/bootstrap.min.js"></script>

    </head>

    <body>
        <div class="header">
            <div class="container">
                <div class="row mt-5 mb-5">
                    <div class="col-md-4">
                        <h1> ROOTS </h1>
                    </div>

                    <div class="col-md-8" id="container"> 
                        <form class="form-inline">
                            <div class="input-group">
                                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-success" type="submit">Search</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">TODAS CATEGORIAS <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">ACESSÓRIOS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">CALÇADOS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="#">MODA NASCULINA</a>
                        </li>
                    </ul>
                </div>
            </div>        
        </nav>       
        
    </body>
        
    <script src="../../js/Mochila/Util.js"></script>
    <script src="../../js/Mochila/xhttp.js"></script>
    <script src="../../js/Controller/CHome.js"></script>
    
</html>
        


