<div id="load" class="load"></div>

<div id="usuarios" class="container content" hidden>
    <div class="row container">
        <!-- <i class="fas fa-user fa-lg mr-2 mt-1"></i> -->
        <h4 id="title"> Listar Usuários </h4>
    </div>

    <hr>

    <div id="table">
        <div class="row container mb-2 menu">
            <button id="btnAdd" class="btn btn-primary mr-1">Adicionar</button>
            <button id="btnEdt" class="btn btn-secondary mr-1" disabled>Editar</button>
        </div>

        <div id="grid"> </div>
    </div>

    <div id="usuario" hidden>
        <form role="form" id="form-usuario" enctype="multipart/form-data" autocomplete="off">
            <div class="row">
                <div class="form-group col-md-1">
                    <label for="txtId">ID</label>
                    <input id="txtId" name="txtId" type="text" class="form-control text-center" readonly>
                </div>

                <div class="form-group col-md-6">
                    <label for="txtNome">Nome</label>
                    <input id="txtNome" name="txtNome" type="text" class="form-control" maxlength="50" required>
                </div>

                <div class="form-group col-md-1">
                    <label for="txtAtivo">Ativo</label>
                    <select id="txtAtivo" name="txtAtivo" class="form-control">
                        <option>S</option>
                        <option>N</option>
                    </select>
                </div>

                <div class="form-group col-md-4">
                    <label for="txtGrupoUsuario">Grupo de Usuário</label>
                    <select id="txtGrupoUsuario" name="txtGrupoUsuario" class="form-control">

                    </select>
                </div>
            </div>
            
            <div class="row">
                <div class="form-group col-md-2">
                    <label for="txtData">Data de Nascimento</label>
                    <input id="txtData" name="txtData" type="date" class="form-control" value="2011-08-19">
                </div>

                <div class="form-group col-md-3">
                    <label for="txtCpf">CPF</label>
                    <input id="txtCpf" name="txtCpf" type="text" class="form-control" maxlength="11" required>
                </div>

                <div class="form-group col-md-3">
                    <label for="txtCelular">Celular</label>
                    <input id="txtCelular" name="txtCelular" type="text" class="form-control" maxlength="11" required>
                </div>

                <div class="form-group col-md-4">
                    <label for="txtEmail">Email</label>
                    <input id="txtEmail" name="txtEmail" type="email" class="form-control" maxlength="50" required>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label for="txtSenha">Senha</label>
                    <input id="txtSenha" name="txtSenha" type="password" class="form-control" maxlength="20" required>
                </div>

                <div class="form-group col-md-6">
                    <label for="txtConfSenha">Confirmar Senha</label>
                    <input id="txtConfSenha" name="txtConfSenha" type="password" class="form-control" maxlength="20" required>
                </div>
            </div>

            <button id="btnSalvar" type="submit" class="btn">Salvar</button>
            <button id="btnCancelar" type="submit" class="btn">Cancelar</button>
        </form>
    </div>

    <div class="footer"> </div>
                            
</div>

<script src="../../js/Controller/CUsuarios.js"></script>
          