<div id="div-content">
    <div class="card">
        <div class="card-header">
            <form role="form" id="form-search" class="navbar-search" enctype="multipart/form-data" autocomplete="off">
                <div class="input-group">
                    <input type="text" id="txtNome" name="txtNome" class="form-control bg border-0" placeholder="Encontrar por..." />
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div id="div-table" class="card-body">
            
        </div>
    </div>                        
</div>
